name = "example"
main = "src/index.tsx"
compatibility_date = "2024-11-13"
compatibility_flags = [ "nodejs_compat" ]

[[d1_databases]]
binding = "db"
database_name = ""
database_id = ""

[dev]
port = 3000
